### ISSUE TITLE
Better restraints for angular CVs?

### ISSUE THREAD

**Issue by Dead-fisher** [deepmodeling/rid-kit#21]
@PKUfjh 
We currently are using simple harmonic restraints on angular CVs, this should be fine most of time. But if angular CV are at the boundary of the periodicity, say -pi or pi, a small change may go across the boundary that the finall harmonic forces are biased by a periodicity.
Ref for PLUMED RESTRAINTS:
https://www.plumed.org/doc-v2.8/user-doc/html/_r_e_s_t_r_a_i_n_t.html

I'm not sure if PLUMED will process difference of torsion internally, but a better and explicit definition would be like:
```
force =  kappa * (diff) ** 2
diff = min(dih-dih_0, 2*pi-(dih-dih_0))
```

Ref: 
https://fastmbar.readthedocs.io/en/latest/butane_PMF.html

**Comment by PKUfjh** [comment]
@Dead-fisher 
Thanks for the insightful suggestion!
It seems that PLUMED automatically deals with the periodicity issue, it can be confirmed by the following experiment:

I did a restrained MD simulation for a configuration with dihedrals near the pi, the CV output through the simulation looks like  this
<img width="724" alt="截屏2023-09-12 14 22 05" src="https://github.com/deepmodeling/rid-kit/assets/32134282/9ca37fe9-3143-4f1a-a5d3-91a18efc2085">

So the first dihedral undergoes a numerical transition from pi to -pi.

But the bias potential output of the PLUMED is normal, without abrupt transition, the figure looks like this:
<img width="671" alt="截屏2023-09-12 14 23 50" src="https://github.com/deepmodeling/rid-kit/assets/32134282/7cb43049-f97d-416e-be11-8a6300e1b842">

This is clearly different from the formula without considering the periodicity, which looks like
<img width="722" alt="截屏2023-09-12 14 24 40" src="https://github.com/deepmodeling/rid-kit/assets/32134282/c836ebb7-49cd-4c8c-aa3d-746835a5fb70">

If we impose the periodicity, the value will be consistent with the PLUMED bias potential output.

**Comment by Dead-fisher** [comment]
That's super clear. Thanks for the experiments.
