### ISSUE TITLE
Setup github action for an automatic unittest when new commits are pushed to the repository

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/rid-kit#4]
With PR #3 RID-kit provides unittests. These tests should be run automatically when the new commits are pushed to the repository. 

A github action for doing this is needed.

**Comment by TablewareBox** [comment]
see https://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html

**Comment by Dead-fisher** [comment]
OK, I will handle them soon.

**Comment by felix5572** [comment]
You may ask @njzjz  for help.  @Dead-fisher

**Comment by njzjz** [comment]
See deepmodeling/dpdispatcher#15.

**Comment by amcadmus** [comment]
> see https://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html

Nor recommend using travis anymore.

**Comment by Dead-fisher** [comment]
Hi all, I have update the .yml file for CI in Action.

**Comment by Dead-fisher** [comment]
Hi all, I have updated .yml file for CI in Action, please review it.

**Comment by Dead-fisher** [comment]
All set
